### ISSUE TITLE
[Bug] Calculated Edit Distance Incorrect When actual or expected is null.

### ISSUE THREAD

**Issue by Joll59** [ryanvolum/word-error-rate#1]
When you Do NOT provide a value for actual or expected as arguments calculatedEdit Distance returns the length of characters in an utterance not the number of words in the utterance. 
Offending Line:  
https://github.com/ryanvolum/word-error-rate/blob/e52696b86e5f699225e22773f9ec08934283f614/src/app.ts#L10

Incoming PR to resolve.

**Comment by ryanvolum** [comment]
@Joll59 I pulled in your PR and revved the package. Version 0.7 should have the fix in!
